name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.3.2
        with:
          sarif: results.sarif
          fail-on: none
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          token: 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
